name: INSTALL_GOOGLE_GENAI

on:
  push:
    branches:
      - main
jobs:
  setup-enviromment:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup node
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm install @google/generative-ai
      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
      - run: node -e "console.log(process.env.API_KEY)"
