name: INSTALL_GOOGLE_GENAI

on:
  push:
    branches:
      - main
jobs:
  setup-enviromment:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup node
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm install @google/generative-ai
      - name: Set environment variable
        run: export const API_KEY = ${{secrets.API_KEY}}
